AWSTemplateFormatVersion: "2010-09-09"

Resources:

  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      TimeoutInMinutes: 10
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            exported-variables:
              - ObjectVersionId
          phases:
            install:
              runtime-versions:
                nodejs: 10
            build:
              commands:
                - cd src;
                - npm ci;
                - zip -r code.zip .;
            post_build:
              commands:
                - du -hs *
                - export ObjectVersionId="$(aws s3api put-object --bucket ${LambdaCodeBucket} --key code.zip --body code.zip --output text --query VersionId)"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-codebuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Effect: Allow
                Resource: !Sub arn:aws:s3:::${LambdaCodeBucket}/*
              - Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Effect: Allow
                Resource: !Sub arn:aws:s3:::${LambdaCodeBucket}
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
                Effect: Allow

Outputs:

  CodeBuildRole:
    Value: !GetAtt CodeBuildRole.Arn

  CodeBuildProject:
    Value: !Ref CodeBuildProject

  LambdaCodeBucket:
    Value: !Ref LambdaCodeBucket