AWSTemplateFormatVersion: 2010-09-09

Parameters:

  DomainName:
    Type: String
    Default: none

  HostedZoneId:
    Type: String
    Default: none

  VpcId:
    Type: AWS::EC2::VPC::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

  LoadBalancerType:
    Type: String
    AllowedValues:
      - classic
      - application
      - network

  LambdaBucket:
    Type: String

  S3FileVersion:
    Type: String

Conditions:

  ApplicationLoadBalancer:
    !Equals
      - !Ref LoadBalancerType
      - application
  
  NetworkLoadBalancer:
    !Equals
      - !Ref LoadBalancerType
      - network
  
  ClassicLoadBalancer:
    !Equals
      - !Ref LoadBalancerType
      - classic

  NotNetworkLoadBalancer:
    !Not
      - !Equals
          - !Ref LoadBalancerType
          - network

Resources:

  NetworkLoadBalancer:
    Condition: NetworkLoadBalancer
    DependsOn: LogsBucketPolicy
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref AWS::StackName
      Scheme: internet-facing
      Type: network
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !Ref LogsBucket
      Subnets: !Ref Subnets

  Certificate:
    Condition: NetworkLoadBalancer
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  TLSListener:
    Condition: NetworkLoadBalancer
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups: 
              - TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: TLS
      Certificates:
        - CertificateArn: !Ref Certificate

  TargetGroup:
    Condition: NetworkLoadBalancer
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      VpcId: !Ref VpcId
      Port: 443
      Protocol: TLS
      TargetType: ip
      Targets: 
        - AvailabilityZone: all
          Id: 172.31.164.1
          Port: 443

  DNSRecord:
    Condition: NetworkLoadBalancer
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
      HostedZoneId: !Ref HostedZoneId
      Comment: !Sub ${AWS::StackName} DNS record for the NLB
      Name: !Ref DomainName
      Type: A

  SecurityGroup:
    Condition: NotNetworkLoadBalancer
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref AWS::StackName
      GroupDescription: !Ref AWS::StackName
      VpcId: !Ref VpcId

  SecurityGroupHTTPInbound:
    Condition: NotNetworkLoadBalancer
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  ClassicLoadBalancer:
    Condition: ClassicLoadBalancer
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName: !Ref AWS::StackName
      Scheme: internet-facing
      AccessLoggingPolicy:
        Enabled: true
        EmitInterval: 5
        S3BucketName: !Ref LogsBucket
      Listeners:
        - InstancePort: '80'
          LoadBalancerPort: '80'
          Protocol: HTTP
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup

  ApplicationLoadBalancer:
    Condition: ApplicationLoadBalancer
    DependsOn: LogsBucketPolicy
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref AWS::StackName
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !Ref LogsBucket
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup

  HTTPListener:
    Condition: ApplicationLoadBalancer
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: application/json
            MessageBody: |
              {
                "statusCode": 200,
                "message": "Wow"
              }
            StatusCode: '200'
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 7
      NotificationConfiguration:
        LambdaConfigurations: 
          - Event: s3:ObjectCreated:*
            Function: !Ref Lambda

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Statement:
          !If
            - NetworkLoadBalancer
            - - Effect: Allow
                Action: s3:PutObject
                Principal:
                  Service: delivery.logs.amazonaws.com
                Resource: !Sub arn:aws:s3:::${LogsBucket}/AWSLogs/${AWS::AccountId}/*
                Condition:
                  StringEquals:
                    s3:x-amz-acl: bucket-owner-full-control
              - Sid: AWSLogDeliveryAclCheck
                Effect: Allow
                Action: s3:GetBucketAcl
                Principal:
                  Service: delivery.logs.amazonaws.com
                Resource: !Sub arn:aws:s3:::${LogsBucket}
            - - Effect: Allow
                Action: s3:PutObject
                Principal:
                  AWS: 783225319266
                Resource: !Sub arn:aws:s3:::${LogsBucket}/AWSLogs/${AWS::AccountId}/*

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 30
      LogGroupName: !Sub /aws/elb/${LoadBalancerType}

  S3EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${LogsBucket}

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 60
      Role: !GetAtt LambdaRole.Arn
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          LOG_GROUP_NAME: !Ref LogGroup
          CLASSIC_ELB_MODE:
            !If
              - ClassicLoadBalancer
              - 'TRUE'
              - !Ref AWS::NoValue
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: code.zip
        S3ObjectVersion: !Ref S3FileVersion

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: !Ref AWS::StackName
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - xray:PutTelemetryRecords
                - xray:PutTraceSegments
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
            - Effect: Allow
              Action:
                - logs:DescribeLogStreams
                - logs:DescribeLogGroups
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub ${LogGroup.Arn}*

Outputs:

  Name:
    Value:
      !If
        - ClassicLoadBalancer
        - !Ref ClassicLoadBalancer
        - !If 
            - ApplicationLoadBalancer
            - !GetAtt ApplicationLoadBalancer.LoadBalancerName
            - !GetAtt NetworkLoadBalancer.LoadBalancerName

  DNSName:
    Value:
      !If
        - ClassicLoadBalancer
        - !GetAtt ClassicLoadBalancer.DNSName
        - !If 
            - ApplicationLoadBalancer
            - !GetAtt ApplicationLoadBalancer.DNSName
            - !GetAtt NetworkLoadBalancer.DNSName

  HostedZoneId:
    Value:
      !If
        - ApplicationLoadBalancer
        - !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        - !If
          - NetworkLoadBalancer
          - !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
          - !Ref AWS::NoValue

  LogsBucket:
    Value: !Ref LogsBucket